name: autocommit-robot

on:
  schedule:
    - cron: "0 0 * * *"
# 注意，时区为美国,大约快来8个小时

jobs:
  bots:
# 虚拟机环境
    runs-on: ubuntu-latest
    steps:
# 获取源码 注意homepage在package配置
      - name: "Checkout code"
        uses: actions/checkout@v3

# 构建并部署环境
      - name: "Set node"
        uses: actions/setup-node@v3
        with:
          node-version: 16.x

# 前端环境
      - name: "Install"
        run: npm install

# 执行
      - name: "Run bash"
        run: node index.js

# 提交
      - name: "Commit"
        uses: EndBug/add-and-commit@v4
        with:
          author_name: mongorolls
          author_email: xuzhichao1618@qq.com
          message: "feat: save robot"
          add: "pictures/*"

        env:
          GITHUB_TOKEN: ${{ secrets.MONGO }}
