name: autocommit-robot

on:
  push:
    branches:
      - main

jobs:
  bots:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout code"
        uses: actions/checkout@v3

      - name: "Set node"
        uses: actions/setup-node@v3
        with:
          node-version: 16.x

      - name: "Install"
        run: npm install

      - name: "Run bash"
        run: node index.js

      - name: "Commit"
        uses: EndBug/add-and-commit@v4
        with:
          author_name: mongorolls
          author_email: xuzhichao1618@qq.com
          message: "feat: save robot"
          add: "pictures/*"

        env:
          GITHUB_TOKEN: ${{ secrets.MONGO }}
